apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: conference-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: local-hub
        clusterUrl: https://kubernetes.default.svc
      - env: staging
        clusterUrl: https://600E2519186BE47FD132A9CBEC671336.gr7.us-east-1.eks.amazonaws.com
      - env: prod
        clusterUrl: https://10DACB96EB7E2D16DDA2025F79BE83E0.gr7.us-east-1.eks.amazonaws.com 
  template:
    metadata:
      name: 'conference-app-{{env}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/conference-app-kkoc/conference-infra.git'
        targetRevision: HEAD
        path: 'kustomize/overlays/{{env}}'
      destination:
        server: '{{clusterUrl}}'
        namespace: 'conference-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
