apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: conference-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - env: staging
        clusterUrl: https://192.168.98.20:6443
      - env: prod
        clusterUrl: https://192.168.98.30:6443
  template:
    metadata:
      name: 'conference-app-{{env}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/conference-app-kkoc/conference-infra.git'
        targetRevision: HEAD
        path: 'kustomize/overlays/{{env}}'
      destination:
        server: '{{clusterUrl}}'
        namespace: 'conference-{{env}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true